### ISSUE TITLE
Visualizing features of VGG-11 with `activation_maximization_with_bilateral_blurring` sample does not work

### ISSUE THREAD

**Issue by umairkhawaja** [farhad-dalirani/PytorchRevelio#2]
Ran the exact same code but ran into an error:

In line 395 in `PytorchRevelio.py` , the input_img dimensions and the gradient dimensions do not match for the channel axis
Image has 3 channels while the gradient has 64

**Comment by umairkhawaja** [comment]
The feature map visualizations for other models are also blank coloured images

**Comment by farhad-dalirani** [comment]
Hello, 

I tested the provided example for "activation maximization with bilateral blurring" that is provided in Readme file. It worked.

Do you use the exact same code? Did you change something in it? 
If you changed something in the code, please give me the code for debugging purposes.

**Comment by umairkhawaja** [comment]
The only change was I used `first_layer_name` as "backbone" as "backbone.0" and saved the output image in a directory

**Comment by farhad-dalirani** [comment]
VGG 11 does not have a layer with the name "backbone.0".

These two variables indicate the first layer and last layer of VGG-11:

```
first_layer_name = 'features.0'
last_layer_name = 'classifier.6'

```

You should not change it for VGG-11. 

This loop in the code, for each linear and convolutional layer, illustrate some of its neurons/filters:

```
    for layer_name in vgg11_net.named_modules():

        layer_name = layer_name[0]
       .
       .
       .
       # from each layer select 8 filter our neurons
        filters_neuron_indexs = np.random.choice([i for i in range(filter_neuron_num)], size=8)
       .
       .
       .
```
